### ISSUE TITLE
GOES 16, 17 bad annotations in summary plots

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#101]
On this day below

http://themis.ssl.berkeley.edu/summary.php?year=2022&month=09&day=04&hour=0024&sumType=goes&type=goes17

http://themis.ssl.berkeley.edu/summary.php?year=2022&month=09&day=04&hour=0024&sumType=goes&type=goes16

 

GOES 16 and 17 should be at the nightside at 10-12 UT (X should be negative and pretty large in absolute value). However X is positive at that time. There is no way, because US and Alaska are at the nightside and GOES West (at least) should be at the nightside.

 

Could you double check why the annotations are incorrect?

 

On other days (say in 2021) annotations are missing:

http://themis.ssl.berkeley.edu/summary.php?year=2021&month=09&day=04&hour=0024&sumType=goes&type=goes16

 

In past years we used MLT and Lshell

http://themis.ssl.berkeley.edu/summary.php?year=2010&month=09&day=04&hour=0024&sumType=goes&type=goes13

 

Maybe we should use a consistent GOES annotations with both GSM XYZ plus MLT below those? (L shell and MLAT does not matter much).

**Comment by nickssl** [comment]
There was a bug in the GSM calculations, the code used degrees instead of rad. This was fixed. Also, MLT values have been added to annotations. 

The code was using calls to spdfgetlocations() to find satellite positions, however, this is slow and unnecessary because the netcdf files for GOES 16-18 contain position information (previously, files for GOES 10-15 did not contain this information). These calls to spdfgetlocations() have now been removed from the code, which resulted in much faster code. 

Code has been changed in the past, some annotations were added but there was no reprocessing of older plots, and as a result, there were inconsistencies about what annotations were included on different dates. Summary plot titles were also inconsistent. This has now been fixed.
 
All summary plots for GOES 16, 17, 18 have been reprocessed, so they should all contain MLT and the correct values for GSM/RE positions.  There were no changes to summary plots for GOES 10-15, only GOES 16-18 have been reprocessed.
