### ISSUE TITLE
Valid CDF file removed after failed download attempt

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#199]
Vassilis encountered a situation where he tried to download data when the network wasn't connected.   When retrying the operation with /no_download, the original file was gone.   This isn't supposed to happen -- what might have gone wrong?

We should check pyspedas at well, in case there's a similar issue there.

**Comment by jameswilburlewis** [comment]
I suspect the file_move call on line 287 of spd_download_file.pro might be where the issue is -- if the portal isn't returning an error code, it looks like we're assuming it's valid data.  So maybe we also need to check there for valid CDFs.

Reproducing the behavior might be challenging (unless someone volunteers to take a bunch of flights on various airlines...for QA purposes. of course!).  Maybe spd_download_file could take another parameter, that would let us pass a mock IDLNetURL object that mimics what we think might be going on with the HTTP portals.

**Comment by jameswilburlewis** [comment]
ChatGPT has some possibly helpful suggestions for captive portal detection.   I like the idea of retrieving a URL with known content and checking whether it matches, then caching the status for the next 5-10 minutes to avoid excessive validation traffic.

https://chatgpt.com/share/673bf500-fd10-800b-aec8-cb122c2bd647

**Comment by nickssl** [comment]
I am afraid that these solutions will create new problems. For example, if we retrieve a test file from the SSL web site, and the SSL web site happens to be down, then the users will not be able to download any files from UCLA or SPDF or anywhere else. And a 5 or 10-minute caching interval can again lead to loss of many local cdf files, if the network gets disconnected during that period. Other solutions that check the response headers, for example the MIME type, can also lead to rejection of proper cdf files when the server headers are not configured properly, but the cdf files themselves do not have any problems. 

I have implemented a solution that checks .cdf or .nc files before moving them from their temporary to their permanent location. I think that this will solve the majority of problems. For example, when we download an HTML file, we usually parse the contents of the response, we don't save the html file as a separate file to be loaded later on, so this issue does not affect these cases; the problem is mainly with the cdf and netcdf files.

**Comment by nickssl** [comment]
The same bug was present in both IDL spedas and python pyspedas, since they work in a similar way.

Both have now been fixed (for cdf and netcdf files).
