### ISSUE TITLE
Issue with SPEDAS GUI on Ubuntu

### ISSUE THREAD

**Issue by supervised** [spedas/bleeding_edge#35]
I received a bug report regarding the SPEDAS GUI on Ubuntu 22.04 (Jammy):

1. data downloads aren't working
2. drop-down menus aren't working well

Not entirely sure, but I think they're using the VM

**Comment by jameswilburlewis** [comment]
User R. Rubia (rubi.r92@gmail.com) reports that the SPEDAS 5.0 Linux VM executable is giving an error that CDF_LIB_INFO is not found.

**Comment by nickssl** [comment]
Newer Ubuntu installations do not contain some Linux libraries required by IDL 8.5.1. I have updated the Linux troubleshooting  section on the wiki:

http://spedas.org/wiki/index.php?title=Downloads_and_Installation#Known_issues_on_Linux

I have also contacted the user, waiting for a response.

**Comment by nickssl** [comment]
It turns out this wasn't a SPEDAS bug, there were two issues in the user's system:
1. IDL_DLM_PATH was specified but it did not include <IDL_DEFAULT>, and as a result, IDL could not find some DLM libraries.
2. Linux library libidn.so.11 was missing.

Both problems were resolved. Solutions are documented in the wiki:
http://spedas.org/wiki/index.php?title=Downloads_and_Installation#Known_issues_on_Linux
