### ISSUE TITLE
missing files in bleeding_edge repo

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#70]
Something seems to be going wrong with the mirroring process -- several files are missing from this repo that are present in the nightly zip files.  For example, these files/directories are missing from general/misc/system:

CSV_Color_Tables
color_table_crib.pro
get_line_colors.pro
line_colors.pro
showct.pro

Other directories are also affected:
general/examples/init_crib_colors.pro

I don't see anything in the github_bleedingedge.py script that would cause this....maybe an intermittent network connection?  But you'd expect it to pick up the missing files on a later run....

**Comment by supervised** [comment]
The script is probably missing a git add command, to add uncommitted files before committing. There might be other problems - I wrote that long before I started using git regularly

**Comment by ericthewizard** [comment]
This should be fixed now. One catch: I had to add a .gitignore file with the directory:

projects/maven/models/

to the top-level of the bleeding_edge directory (where the git repo lives, and the latest files are copied to after downloading the zip), because there are some files in there that are too large to commit to GitHub (>100MB).
