### ISSUE TITLE
THEMIS-E scpot calculations for dayside/outside of tail

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#73]
From Vassilis:

I have been looking at the scpot calculation on TH-E which does not have EFI-determined scpot values. While the procedure was working really well in the tail (September/October 2022), now on the dayside there are problems (check last couple of months), and the scpot does not reflect the true knee in the electron spectrum between perceived photoelectrons and ambient electrons. As a result, the ion/electron and scpot-determined densities differ significantly,  I am wondering if you could look into why and fix it?

**Comment by jimm02** [comment]
There was a problem with the IDL setup for the L2 process. The script create_probe_l1tol2_5days.ksh called a configuration script called overplot.bourne, which set up IDL 6.3. Later in the create_probe_l1tol2_5days.ksh script the setup script for IDL 8.5.1 is called.  It turns out that calling the IDL 8.5.1 setup did not set all of the functions to IDL 8.5.1 versions. 

In particular, the interpol function remained the IDL 6.3 version. This gave bad results in the program thm_esa_est_dist2scpot2.pro where the electron distribution is interpolated to a high resolution energy grid, and resulted in overestimates of the spacecraft potential. Data after 2023-02-15 were affected. (Prior to this the THEMIS E files had been processed using a different script which only set up IDL 8.5.1.)

The script is now fixed, the overplot.bourne call is commented out, and the setup now only sets up IDL 8.5.1. The data post 2023-02-15 is reprocessing.
