### ISSUE TITLE
Rewrite sosmag load routine & crib sheet to use CSV files downloaded separately

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#93]
It will probably take some time for IDL to implement the changes we need to support downloading SOSMAG data from the ESA HAPI server.  In the meantime, we should modify the load routine and crib sheet to be able to use CSV files downloaded via external tools, as we've done for the online summary plots.

**Comment by nickssl** [comment]
Completed. New routines load data from CSV files that can be downloaded manually from the ESA web server. Older routines for direct HAPI server access were moved into their own directory and currently, they do not work because IDL cannot complete the authentication used by the ESA HAPI server. In the future, if the HAPI authentication method changes, or if a newer IDL version supports setting CURL parameters, we can fix these procedures.
